// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNCxcZAT9gBBaAXMoOVGP02CBQ2YZTMKY',
    appId: '1:337501868219:web:34f9bf2d6898eb24d6599e',
    messagingSenderId: '337501868219',
    projectId: 'rivaan-reddit',
    authDomain: 'rivaan-reddit.firebaseapp.com',
    storageBucket: 'rivaan-reddit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIimBBL42ILM5XoOZiGN_hvVFaM-7ShHQ',
    appId: '1:337501868219:android:729093095d012827d6599e',
    messagingSenderId: '337501868219',
    projectId: 'rivaan-reddit',
    storageBucket: 'rivaan-reddit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMfSiKlXEGLXLQYWXwiLYaCzr0QqboA8',
    appId: '1:337501868219:ios:f43bfb03ae0f7e89d6599e',
    messagingSenderId: '337501868219',
    projectId: 'rivaan-reddit',
    storageBucket: 'rivaan-reddit.appspot.com',
    iosClientId: '337501868219-5k035amgb3bhe8th8a2t40so4lsf264n.apps.googleusercontent.com',
    iosBundleId: 'com.example.rivaanJReddit',
  );
}
